AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for bingo-maker-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 100

Resources:
  NetCodeWebAPIServerless:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: A simple example includes a .NET Core WebAPI App with DynamoDB table.
      CodeUri: ./src/ServerlessAPI/
      Handler: ServerlessAPI
      Runtime: dotnet8
      MemorySize: 1024
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          GAME_CONFIG_TABLE: !Ref GameConfigsTable
          GAME_BOARD_TABLE: !Ref GameBoardsTable
          USE_DYNAMODB_LOCAL: "false"
          Auth0__Domain: dev-rqtd0acytoaoqh1w.us.auth0.com
          Auth0__Audience: https://bingo-api.jd-sanchez.com
      Policies:
        # Give Create/Read/Update/Delete Permissions to the Tables
        - DynamoDBCrudPolicy:
            TableName: !Ref GameConfigsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref GameBoardsTable
      Events:
        ProxyResource:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: "2.0"
            Path: /{proxy+}
            Method: ANY

  GameConfigsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: GameConfigs
      PrimaryKey:
        Name: GameId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  GameBoardsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GameBoards
      AttributeDefinitions:
        - AttributeName: GameId
          AttributeType: S
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: GameId
          KeyType: HASH
        - AttributeName: UserId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
